name: Publish to PyPI on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build sdist and wheel
        run: python -m build
      - name: Verify metadata
        run: |
          python -m pip install twine
          python -m twine check dist/*
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  # Set repository secret PYPI_API_TOKEN to your PyPI token for publishing
  # with:
  #   password: ${{ secrets.PYPI_API_TOKEN }}
